title: Testing Pathways
description: An open source learning platform for test engineers, allowing them to learn by following helpfull pathways
theme: just-the-docs

url: https://TestingPathways.github.io

aux_links:
  Template Repository: hhttps://github.com/TestingPathways/testingpathways
